#!/bin/bash
echo "=========================================="
echo "Starting Kubernetes VMs provisioning..."
echo "=========================================="
vagrant up k8s-node-1 k8s-node-2
echo ""
echo "Setting up k8s-node-1..."
vagrant ssh k8s-node-1 -c "sudo bash /vagrant/scripts/setup-k8s-node.sh"
echo ""
echo "Setting up k8s-node-2..."
vagrant ssh k8s-node-2 -c "sudo bash /vagrant/scripts/setup-k8s-node.sh"
echo ""
echo "=========================================="
echo "✅ Kubernetes VMs setup complete!"
echo "=========================================="
echo ""
echo "🚀 Next steps:"
echo "1. SSH into master: vagrant ssh k8s-node-1"
echo "2. Initialize cluster:"
echo "   sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.20"
echo ""
