#!/bin/bash
echo "=========================================="
echo "Starting Monitoring VM provisioning..."
echo "=========================================="
vagrant up monitoring
echo ""
echo "Running setup script inside monitoring VM..."
vagrant ssh monitoring -c "sudo bash /vagrant/scripts/setup-monitoring.sh"
echo ""
echo "=========================================="
echo "✅ Monitoring VM setup complete!"
echo "=========================================="
echo ""
echo "📍 Access Points:"
echo "   Prometheus: http://192.168.56.30:9090"
echo "   Grafana:    http://192.168.56.30:3000"
echo ""
echo "🔑 Grafana Login: admin/admin"
echo ""
