#!/bin/bash
echo "=========================================="
echo "Starting ALL VMs provisioning..."
echo "=========================================="
vagrant up
echo ""
echo "[1/3] Setting up Jenkins VM..."
vagrant ssh jenkins-app -c "sudo bash /vagrant/scripts/setup-jenkins-app.sh"
echo ""
echo "[2/3] Setting up Kubernetes VMs..."
vagrant ssh k8s-node-1 -c "sudo bash /vagrant/scripts/setup-k8s-node.sh"
vagrant ssh k8s-node-2 -c "sudo bash /vagrant/scripts/setup-k8s-node.sh"
echo ""
echo "[3/3] Setting up Monitoring VM..."
vagrant ssh monitoring -c "sudo bash /vagrant/scripts/setup-monitoring.sh"
echo ""
echo "=========================================="
echo "✅ ALL VMs setup complete!"
echo "=========================================="
echo ""
echo "📍 Access Points:"
echo "   Jenkins:    http://192.168.56.10:8080"
echo "   Prometheus: http://192.168.56.30:9090"
echo "   Grafana:    http://192.168.56.30:3000"
echo ""
